name: Create Progress Chart from Automated Test Case Database

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install requests
        pip install matplotlib==3.5.0
    - name: Generate graph
      run: python NotionSync.py
      env:
        INTEGRATION_TOKEN: ${{ secrets.INTEGRATION_TOKEN }}
    - name: push graph image to repo
      run: |
        git config --global user.name "pengwings"
        git config --global user.email "brianyu012@gmail.com"
        git add graph.png
        git commit -m "updated graph"
        git push
